### ISSUE TITLE
python2 set-dictionary issue

### ISSUE THREAD

**Issue by tomleo** [myint/scspell#25]
``` console
tom@computer:~/$ scspell --set-dictionary=/home/tom/Dropbox/work/data/spelling.txt
Traceback (most recent call last):
  File "/home/tom/hacking/energysage/env/bin/scspell", line 11, in <module>
    sys.exit(main())
  File "/home/tom/hacking/energysage/env/local/lib/python2.7/site-packages/scspell/__init__.py", line 899, in main
    set_dictionary(args.dictionary)
  File "/home/tom/hacking/energysage/env/local/lib/python2.7/site-packages/scspell/__init__.py", line 648, in set_dictionary
    config.write(f)
  File "/usr/lib/python2.7/ConfigParser.py", line 414, in write
    fp.write("\n")
TypeError: write() argument 1 must be unicode, not str
tom@computer:~/$ Python 2.7.13
tom@computer:~/$ pip freeze | grep -i scspell
scspell3k==2.1
```

**Comment by kkmuffme** [comment]
having the same issue

```
Traceback (most recent call last):
  File "/usr/bin/scspell", line 9, in <module>
    load_entry_point('scspell3k==2.1', 'console_scripts', 'scspell')()
  File "/usr/lib/python2.7/site-packages/scspell/__init__.py", line 899, in main
    set_dictionary(args.dictionary)
  File "/usr/lib/python2.7/site-packages/scspell/__init__.py", line 648, in set_dictionary
    config.write(f)
  File "/usr/lib64/python2.7/ConfigParser.py", line 414, in write
    fp.write("\n")
TypeError: must be unicode, not str
```

**Comment by giosad** [comment]
fixed here: https://github.com/giosad/scspell/tree/feature/config_parser_issue_py2
I just used the https://pypi.org/project/configparser/ and made minimal [modifications](https://github.com/giosad/scspell/commit/b30ba3bfe5716e5511670c1b86c6ba60d7f75dca) to make the scspell to work with it.

I don't know to how to specify the dependency for pip for python 2 only through.
